baseURL = 'https://aws-user-group.berlin/'
languageCode = 'en-us'
title = 'AWS User Group Berlin'
theme = "awsug"
summaryLength = '35'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team/"
    weight = 30
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 40
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 50

[deployment]

[[deployment.targets]]
name = "production"
URL = "s3://aws-user-group.berlin?region=eu-central-1"
cloudFrontDistributionID = "E2RPNIMVK40BRV"